# Please see first _config.yml
# The config here is dedicated to your website, once in wild, real production environment
# Properties here will overrides those in _config.yml


baseurl: "/paul" # the subpath of your site, e.g. /blog
#google_analytics: "" # example of custom prop you may add : your google analytics ID. You also need to import the JS script to make it work.
